### ISSUE TITLE
与savor主题的 高亮挖空功能冲突了

### ISSUE THREAD

**Issue by Ctipsy** [TCOTC/siyuan-plugin-hsr-mdzz2048-fork#18]
![image](https://github.com/user-attachments/assets/99f9f246-9413-4374-b3cc-8f99614c1f57)

原来这里 默认功能是 高亮，如果安装了savor主题可以设置挖空隐藏内容，安装了高亮搜索插件后，这个按钮变成了搜索

**Comment by TCOTC** [comment]
我的 Savor 怎么没有顶栏按钮？你关闭插件之后重启思源再录个屏给我看看 Savor 的顶栏按钮？

https://github.com/user-attachments/assets/395c2a94-302c-43c5-a1ec-0ba3447398ee

**Comment by TCOTC** [comment]
Savor 主题不会添加你箭头指着的这个按钮，应该跟 Savor 主题没关系，建议检查一下是否是其他代码片段或者插件与本插件冲突。

我目前没有复现问题，先关闭了。

**Comment by Ctipsy** [comment]
我重新走了下流程，确实和savor主题无关，而是思源自带的 标注（alt+D）功能；
所以不复用图标，另起一个就可以解决。 我看8/10的版本已经改了，感谢 🌼
