### ISSUE TITLE
代码块内无语法高亮的文本在搜索时无法移动到界面中央

### ISSUE THREAD

**Issue by liumumu666** [TCOTC/siyuan-plugin-hsr-mdzz2048-fork#8]
作者您好，关于搜索代码块中内容的问题反馈

**如图，代码块内的所搜，第一个匹配的会跳转，往后的不会。代码块之外的正常**

![image](https://github.com/TCOTC/siyuan-plugin-hsr-mdzz2048-fork/assets/40857311/dd6aeeef-1590-43f9-9534-f7d4b5f07518)

**Comment by TCOTC** [comment]
这个我研究不明白，暂时不管了

**Comment by iamqiz** [comment]
复现不了,  代码块的行号,我这里是搜索不到的, 它是css伪元素产生的,不是文本节点,按理讲,是搜索不到的

**Comment by TCOTC** [comment]
> 复现不了, 代码块的行号,我这里是搜索不到的, 它是css伪元素产生的,不是文本节点,按理讲,是搜索不到的

楼主那个应该不是思源自带的行号
